// <auto-generated />
namespace SMPR_testing.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class v2_Add_PassedTestsTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v2_Add_PassedTestsTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201406021239264_v2_Add_PassedTestsTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
