// <auto-generated />
namespace SMPR_testing.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class v5_prices_for_task_and_answer_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v5_prices_for_task_and_answer_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201406082208463_v5_prices_for_task_and_answer_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
